// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fhesrv.proto

package fhe

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EvalRequest struct {
	Request              []byte   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Fromtimestamp        int64    `protobuf:"varint,2,opt,name=fromtimestamp,proto3" json:"fromtimestamp,omitempty"`
	Totimestamp          int64    `protobuf:"varint,3,opt,name=totimestamp,proto3" json:"totimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvalRequest) Reset()         { *m = EvalRequest{} }
func (m *EvalRequest) String() string { return proto.CompactTextString(m) }
func (*EvalRequest) ProtoMessage()    {}
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c47bc0bfb9ce40c, []int{0}
}

func (m *EvalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvalRequest.Unmarshal(m, b)
}
func (m *EvalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvalRequest.Marshal(b, m, deterministic)
}
func (m *EvalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvalRequest.Merge(m, src)
}
func (m *EvalRequest) XXX_Size() int {
	return xxx_messageInfo_EvalRequest.Size(m)
}
func (m *EvalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvalRequest proto.InternalMessageInfo

func (m *EvalRequest) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *EvalRequest) GetFromtimestamp() int64 {
	if m != nil {
		return m.Fromtimestamp
	}
	return 0
}

func (m *EvalRequest) GetTotimestamp() int64 {
	if m != nil {
		return m.Totimestamp
	}
	return 0
}

type EvalReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Response             []byte   `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvalReply) Reset()         { *m = EvalReply{} }
func (m *EvalReply) String() string { return proto.CompactTextString(m) }
func (*EvalReply) ProtoMessage()    {}
func (*EvalReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c47bc0bfb9ce40c, []int{1}
}

func (m *EvalReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvalReply.Unmarshal(m, b)
}
func (m *EvalReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvalReply.Marshal(b, m, deterministic)
}
func (m *EvalReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvalReply.Merge(m, src)
}
func (m *EvalReply) XXX_Size() int {
	return xxx_messageInfo_EvalReply.Size(m)
}
func (m *EvalReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EvalReply.DiscardUnknown(m)
}

var xxx_messageInfo_EvalReply proto.InternalMessageInfo

func (m *EvalReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EvalReply) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

type UploadRequest struct {
	File                 []byte   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c47bc0bfb9ce40c, []int{2}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *UploadRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type UploadReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadReply) Reset()         { *m = UploadReply{} }
func (m *UploadReply) String() string { return proto.CompactTextString(m) }
func (*UploadReply) ProtoMessage()    {}
func (*UploadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c47bc0bfb9ce40c, []int{3}
}

func (m *UploadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadReply.Unmarshal(m, b)
}
func (m *UploadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadReply.Marshal(b, m, deterministic)
}
func (m *UploadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadReply.Merge(m, src)
}
func (m *UploadReply) XXX_Size() int {
	return xxx_messageInfo_UploadReply.Size(m)
}
func (m *UploadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadReply.DiscardUnknown(m)
}

var xxx_messageInfo_UploadReply proto.InternalMessageInfo

func (m *UploadReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EvalRequest)(nil), "fhe.EvalRequest")
	proto.RegisterType((*EvalReply)(nil), "fhe.EvalReply")
	proto.RegisterType((*UploadRequest)(nil), "fhe.UploadRequest")
	proto.RegisterType((*UploadReply)(nil), "fhe.UploadReply")
}

func init() {
	proto.RegisterFile("fhesrv.proto", fileDescriptor_2c47bc0bfb9ce40c)
}

var fileDescriptor_2c47bc0bfb9ce40c = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x51, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x75, 0xad, 0xac, 0x76, 0xda, 0x95, 0x65, 0x4e, 0xa5, 0xa7, 0x25, 0x08, 0x7a, 0xaa, 0xa0,
	0xde, 0xc5, 0x83, 0xfb, 0x01, 0x01, 0x3f, 0x20, 0x62, 0xaa, 0x0b, 0xed, 0x4e, 0x4c, 0xe2, 0x82,
	0x7f, 0x6f, 0x32, 0x31, 0x6b, 0x7b, 0xf1, 0x94, 0x79, 0x6f, 0x66, 0xde, 0x7b, 0x4c, 0xa0, 0xee,
	0x3f, 0xb4, 0xb3, 0x87, 0xce, 0x58, 0xf2, 0x84, 0x45, 0x40, 0x82, 0xa0, 0x7a, 0x3e, 0xa8, 0x41,
	0xea, 0xcf, 0x2f, 0xed, 0x3c, 0x36, 0x70, 0x6e, 0x53, 0xd9, 0x2c, 0x36, 0x8b, 0x9b, 0x5a, 0x66,
	0x88, 0x57, 0xb0, 0xea, 0x2d, 0x8d, 0x7e, 0x37, 0x06, 0xa4, 0x46, 0xd3, 0x9c, 0x86, 0x7e, 0x21,
	0xe7, 0x24, 0x6e, 0xa0, 0xf2, 0xf4, 0x37, 0x53, 0xf0, 0xcc, 0x94, 0x12, 0x4f, 0x50, 0x26, 0x43,
	0x33, 0x7c, 0x47, 0xbb, 0xc0, 0x3b, 0xf5, 0xae, 0xd9, 0xae, 0x94, 0x19, 0x62, 0x0b, 0x17, 0x56,
	0x3b, 0x43, 0x7b, 0xa7, 0xd9, 0xa9, 0x96, 0x47, 0x2c, 0x1e, 0x61, 0xf5, 0x62, 0x06, 0x52, 0x6f,
	0x39, 0x35, 0xc2, 0x59, 0xbf, 0x1b, 0xf4, 0x6f, 0x64, 0xae, 0xa3, 0x40, 0x7c, 0xf7, 0x6a, 0x4c,
	0x02, 0xa5, 0x3c, 0x62, 0x71, 0x0d, 0x55, 0x16, 0xf8, 0x37, 0xc5, 0x1d, 0xc1, 0x72, 0xcb, 0x27,
	0xc3, 0xdb, 0x14, 0x7b, 0x1b, 0x24, 0x1c, 0xae, 0xbb, 0x70, 0xba, 0x6e, 0x72, 0xb7, 0xf6, 0x72,
	0xc2, 0x04, 0x49, 0x71, 0x82, 0x0f, 0x00, 0xc9, 0x23, 0xae, 0x20, 0x72, 0x7f, 0x96, 0xba, 0x5d,
	0xcf, 0x38, 0xde, 0x7a, 0x5d, 0xf2, 0xd7, 0xdc, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x62,
	0x36, 0xc9, 0xaa, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FhesrvClient is the client API for Fhesrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FhesrvClient interface {
	EvalFiles(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalReply, error)
	UploadFile(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadReply, error)
}

type fhesrvClient struct {
	cc grpc.ClientConnInterface
}

func NewFhesrvClient(cc grpc.ClientConnInterface) FhesrvClient {
	return &fhesrvClient{cc}
}

func (c *fhesrvClient) EvalFiles(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalReply, error) {
	out := new(EvalReply)
	err := c.cc.Invoke(ctx, "/fhe.Fhesrv/EvalFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fhesrvClient) UploadFile(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadReply, error) {
	out := new(UploadReply)
	err := c.cc.Invoke(ctx, "/fhe.Fhesrv/UploadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FhesrvServer is the server API for Fhesrv service.
type FhesrvServer interface {
	EvalFiles(context.Context, *EvalRequest) (*EvalReply, error)
	UploadFile(context.Context, *UploadRequest) (*UploadReply, error)
}

// UnimplementedFhesrvServer can be embedded to have forward compatible implementations.
type UnimplementedFhesrvServer struct {
}

func (*UnimplementedFhesrvServer) EvalFiles(ctx context.Context, req *EvalRequest) (*EvalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvalFiles not implemented")
}
func (*UnimplementedFhesrvServer) UploadFile(ctx context.Context, req *UploadRequest) (*UploadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}

func RegisterFhesrvServer(s *grpc.Server, srv FhesrvServer) {
	s.RegisterService(&_Fhesrv_serviceDesc, srv)
}

func _Fhesrv_EvalFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FhesrvServer).EvalFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fhe.Fhesrv/EvalFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FhesrvServer).EvalFiles(ctx, req.(*EvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fhesrv_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FhesrvServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fhe.Fhesrv/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FhesrvServer).UploadFile(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fhesrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fhe.Fhesrv",
	HandlerType: (*FhesrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvalFiles",
			Handler:    _Fhesrv_EvalFiles_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _Fhesrv_UploadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fhesrv.proto",
}
